"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def even_fibonacci_numbers():
    # First two terms are 1, 2
    n1, n2 = 1, 2
    fib_sum = 2

    while (n1 + n2) < 4000000:
        # Updating terms
        n1, n2 = n2, n1 + n2

        if n2 % 2 == 0:
            fib_sum += n2

    return fib_sum


print(even_fibonacci_numbers())
